@ECHO OFF
:: This batch file deletes the cache files from Sims 4, assuming they are saved to the default location and this .bat is in the Sims 4 directory. It also looks for some mod caches but those must be organized in a certain way: "The Sims 4\mods\mods [author name] {FIXES}\" for most mods and "The Sims 4\mods\[mod name]\" for others.
:: Written by Dinoval
:: Updated November 20th 2021
TITLE Cache Clearing Tool
ECHO This window will close automatically upon completion.
ECHO Now deleating basegame caches.
ECHO Deleating localthumbcache.package...
DEL localthumbcache.package
ECHO Deleating avatarcache.package...
DEL avatarcache.package
ECHO Deleating lastException.txt...
DEL lastException*
ECHO Deleating lastUIException.txt...
DEL lastUIException*
ECHO Deleating lastCrash.txt...
DEL lastCrash*
ECHO Deleating lastCleanException.txt...
DEL lastCleanException*
ECHO Deleating BE-ExceptionReport.html...
DEL BE-ExceptionReport*
ECHO Now deleating common mod caches.
ECHO Deleating mc_lastexception.html...
DEL "%~dp0\Mods\MC Command Center\mc_lastexception.html"
ECHO Deleating mc_cmd_center.log...
DEL "%~dp0\Mods\MC Command Center\mc_cmd_center.log"
ECHO Deleating spellbook_injector.log...
DEL "%~dp0\Mods\spellbook_injector.log"
ECHO Now deleating uncommon mod caches.
ECHO Deleating NC4T_PickpocketingMod.log...
DEL "%~dp0\Mods\mods NC4T\NC4T_PickpocketingMod.log"
ECHO Done!